version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./shield/pg-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    
  redis:
    image: redis:latest
    container_name: auth_redis_container
    ports:
      - '6378:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  shield-go-app:
    build: ./shield
    container_name: auth_shield_app_container
    ports:
      - '8080:8080'
      - '8010:8010'
      - '8011:8011'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bash -c "go run ./migrator/main.go && go run ./main.go ./packages.go" 


  react-app:
    build: ./shield-fe-app
    container_name: auth_shield_fe_app_container
    ports:
      - '3000:80'

           
  